name: CarbonBlackSegmentation
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python>=3.8
- opencv
- pillow
- matplotlib
- tqdm
- scikit-learn
- pytorch
- cudatoolkit=11.0
- ignite
- albumentations
- fire
- future
- tensorboard
- tensorboardx
- protobuf
- jupyter
- pip
- pip:
    - segmentation-models-pytorch
    - trains
    - opencv-python
