name: CarbonBlackSegmentation
channels:
- pytorch-nightly
- conda-forge
- defaults
dependencies:
- python
- pillow
- matplotlib
- tqdm
- scikit-learn
- pytorch=1.5.*
- cudatoolkit=10.2
- ignite
- albumentations
- fire
- future
- tensorboardx
- protobuf
- pip
- pip:
    - segmentation-models-pytorch
    - trains
