name: CarbonBlackSegmentation
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python
- opencv
- pillow
- matplotlib
- tqdm
- scikit-learn
- pytorch
- cudatoolkit=10.2
- ignite
- albumentations
- fire
- future
- tensorboardx
- protobuf
- pip
- pip:
    - segmentation-models-pytorch
    - trains
